In [4]:
from random import randint
randint(0,30)

4

In [7]:
import numpy as np 

npTempCel = np.random.randint(1,30,100)
npTempCel

array([15,  6, 19, 27, 12, 21, 22, 12, 28,  5, 15, 23, 20,  6, 27, 18,  8,
       19, 12, 24, 11, 26, 20, 22, 10,  5, 17, 20, 12, 11, 12,  3,  9, 26,
       17,  8,  7, 10,  7,  6, 12, 13, 23, 22,  4, 11,  8,  2,  6,  5, 25,
       19, 29, 24, 28, 26,  4, 15, 14,  3, 28, 11, 22,  5, 20, 28,  4,  8,
       19, 22, 14, 12,  9,  1,  4, 12,  6, 20, 29,  8, 11, 14,  9,  4, 13,
        2,  1, 12, 11, 20, 26,  3, 23, 24, 29, 11, 11, 12,  6, 16])

In [8]:
npTempFer = npTempCel*9/5+32
npTempFer

array([59. , 42.8, 66.2, 80.6, 53.6, 69.8, 71.6, 53.6, 82.4, 41. , 59. ,
       73.4, 68. , 42.8, 80.6, 64.4, 46.4, 66.2, 53.6, 75.2, 51.8, 78.8,
       68. , 71.6, 50. , 41. , 62.6, 68. , 53.6, 51.8, 53.6, 37.4, 48.2,
       78.8, 62.6, 46.4, 44.6, 50. , 44.6, 42.8, 53.6, 55.4, 73.4, 71.6,
       39.2, 51.8, 46.4, 35.6, 42.8, 41. , 77. , 66.2, 84.2, 75.2, 82.4,
       78.8, 39.2, 59. , 57.2, 37.4, 82.4, 51.8, 71.6, 41. , 68. , 82.4,
       39.2, 46.4, 66.2, 71.6, 57.2, 53.6, 48.2, 33.8, 39.2, 53.6, 42.8,
       68. , 84.2, 46.4, 51.8, 57.2, 48.2, 39.2, 55.4, 35.6, 33.8, 53.6,
       51.8, 68. , 78.8, 37.4, 73.4, 75.2, 84.2, 51.8, 51.8, 53.6, 42.8,
       60.8])

In [17]:
# npTempFer[npTempFer<50]

mask = npTempFer<50
npTempFer[mask]

array([42.8, 41. , 42.8, 46.4, 41. , 37.4, 48.2, 46.4, 44.6, 44.6, 42.8,
       39.2, 46.4, 35.6, 42.8, 41. , 39.2, 37.4, 41. , 39.2, 46.4, 48.2,
       33.8, 39.2, 42.8, 46.4, 48.2, 39.2, 35.6, 33.8, 37.4, 42.8])

In [18]:
npDriveData = np.random.randint(0,100,[10,6])
npDriveData

array([[ 2, 47, 65, 10, 21, 40],
       [55, 30, 33, 47, 60, 42],
       [11,  9, 47,  9, 24, 68],
       [56, 56, 12, 87, 45, 28],
       [21, 41, 31,  4,  0, 24],
       [70, 51, 29, 18, 76, 41],
       [60, 22, 95, 89, 68, 45],
       [ 7, 72, 75, 88, 68, 67],
       [27, 89, 49, 68, 23, 23],
       [82, 54, 30,  6, 26, 46]])

In [26]:
npDriveData[:,1]>55

array([False, False, False,  True, False, False, False,  True,  True,
       False])

In [27]:
mask1 = npDriveData>40
mask2 = npDriveData<20

npDriveData[(mask1 | mask2)]

array([ 2, 47, 65, 10, 55, 47, 60, 42, 11,  9, 47,  9, 68, 56, 56, 12, 87,
       45, 41,  4,  0, 70, 51, 18, 76, 41, 60, 95, 89, 68, 45,  7, 72, 75,
       88, 68, 67, 89, 49, 68, 82, 54,  6, 46])